name: extreme_flutter_lints
description: LM Labs recommended lints for Flutter apps, packages, and plugins to encourage good coding practices.
repository: https://github.com/glemartret/extreme_flutter_lints
issue_tracker: https://github.com/glemartret/extreme_flutter_lints/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
version: 0.0.3

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter_lints: ^3.0.1
  # Code is not allowed in this package. Do not add any dependencies or dev_dependencies.